// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDQ6T_cYzmcBo69gLCLx9HO-V8D15gcD8',
    appId: '1:728678249211:web:cf8c074dee039d6d84f65e',
    messagingSenderId: '728678249211',
    projectId: 'lab10-9e62d',
    authDomain: 'lab10-9e62d.firebaseapp.com',
    storageBucket: 'lab10-9e62d.appspot.com',
    measurementId: 'G-HQZ7Y6KECC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMSou5CEx8CKEN7JLUhlH1GOl9YLCUjEQ',
    appId: '1:728678249211:android:386553139d019bdb84f65e',
    messagingSenderId: '728678249211',
    projectId: 'lab10-9e62d',
    storageBucket: 'lab10-9e62d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHMe__UXDZ6sctGZyajVW4PRejqW0ToI0',
    appId: '1:728678249211:ios:bb9395e99a9c695184f65e',
    messagingSenderId: '728678249211',
    projectId: 'lab10-9e62d',
    storageBucket: 'lab10-9e62d.appspot.com',
    iosBundleId: 'com.example.lab112',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHMe__UXDZ6sctGZyajVW4PRejqW0ToI0',
    appId: '1:728678249211:ios:3b72dc31590e121084f65e',
    messagingSenderId: '728678249211',
    projectId: 'lab10-9e62d',
    storageBucket: 'lab10-9e62d.appspot.com',
    iosBundleId: 'com.example.lab112.RunnerTests',
  );
}
